config/routes.rb
Rails.application.routes.draw do
  devise_for :u_sers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :books do
	resources :reviews
end
root 'books#index'

post 'books/search', to: 'books#search'

require 'sidekiq/web'
mount Sidekiq::Web => "/sidekiq"

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :u_ser
	belongs_to :category
	has_many :reviews

	has_attached_file :book_img, styles: { :book_index => "250x350>", :book_show => "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/

     include Humanizer
  require_human_on :create
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show, :update, :destroy, :edit]
	before_action :authenticate_u_ser!, only: [:new, :edit]

	def index
		
		if params[:format]
			@books = Book.where(id: params[:format].split("/"))

		else
	 	if params[:category].blank?
	 	@books = Book.all.order("created_at DESC")
		else
		@category_id = Category.find_by(name: params[:category]).id
		@books = Book.where(category_id: @category_id).order("created_at DESC") 
		end
		 end
	end	

	def new

	@book = current_u_ser.books.build
	@categories = Category.all.map{ |c| [c.name, c.id]}

	end	


	def show 
		if @book.reviews.blank?
			@average_review = 0
		else
			@average_review = @book.reviews.average(:rating).round(2)
		end
	end

	

	def create
		@book = current_u_ser.books.build(book_params)
		@book.category_id = params[:category_id]
		
		if @book.save
			redirect_to root_path
		else
			render 'new'
		 end
		end
	
	def edit
	@categories = Category.all.map{ |c| [c.name, c.id]}

	end

	def search
	
	@search = Book.where("title LIKE '%#{params[:search][:search]}%'") 
		
	redirect_to books_path(@search.ids )

	end


	def update
		@book.category_id = params[:category_id]
		if @book.update(book_params)
		redirect_to book_path(@book)
		else
		render 'edit'
		end	
	end


	def destroy
		@book.destroy
		redirect_to root_path
	end

def find_book
	@book = Book.find(params[:id])

end	


private 

def book_params
	params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
end

def search_params
	params[:search][:search]
	#params.require(:search).permit(:search)
end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book,  :html => {:multipart => true }  do |f| %>

<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a Category")%>
 <%= f.file_field :book_img %>
 <%= f.input :title, label:"Book Title" %>
 <%= f.input :description %>
 <%= f.input :author %>
 <%= f.label :humanizer_answer, @book.humanizer_question %>
<%= f.text_field :humanizer_answer %>
<%= f.hidden_field :humanizer_question_id %>
 <%= f.button :submit, class: "btn-custom2" %> 

<% end %>

app/views/books/edit.html.erb
<h1> Edit Book </h1>
<div class="col-md-6 col-md-offset-3">
		<div class="edit-book-form">

	<%= simple_form_for @book, :html => {:multipart => true } do |f| %>

	<%=  f.select :category_id, @categories %>
	<%= f.file_field :book_img %>
	<%= f.input :title, label:"Book Title" %>
	<%= f.input :description %>
	<%= f.input :author %>
	<%= f.button :submit, class: "btn-custom2" %> 

	 </div>
 </div>

<% end %>

app/views/books/index.html.erb
<h1 class="Category">
<%= params[:category] %>
</h1>
<% if @books.count == 0 %>
	<%= "There are no books currently in this category"%>

<% else %>	
 	<div class="row">

		<% @books.each do |book| %>

		<div class="col-md-3" >
		<%= link_to image_tag(book.book_img.url(:book_index), class: "book"), book_path(book) %>
		</div>
	<% end %>
	
 </div>
<% end %>

 

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="new-book-form">

	<h1> New Book </h1>

	<%= render 'form' %>

	</div>
</div>

app/views/books/show.html.erb
<div class="row"> 
		<div class="col-md-4">
		<%= image_tag @book.book_img.url(:book_show), class: "book-show" %>
		</div>

		<div class="col-md-8">
		<div class="book-info">
		<h2 class="book-title"><%= @book.title %></h2>
		<h3 class="book-author"><span>From </span><%= @book.author %></h3>
		<h4 class="average-rating">Average Rating</h4>
		<div class="average-review-rating" data-score=<%= @average_review %>></div>
		<span class="number-of-reviews" style="color:darkolivegreen;font-weight:bold"> Based on reviews: <%= @book.reviews.count %> reviews</span>	
		<p style="color:blue;font-weight: b">Average score for sentiments: <%= @book.reviews.sum('sentiment_score').round(2) %>	</p>
		<p class="book-desc"><%= @book.description %></p>
		<p>Category: <%= @book.category.name %></p>
		</div>
	
		</div>

</div>

<div class="row"> 
		<div class="col-md-4">
				<div class="reviews">	
		
				<h1> Reviews </h1>	
				<%= link_to "Add Review", new_book_review_path(@book) %>
				
				<%= render @book.reviews.order("created_at DESC") %>

				</div>
			</div>
	
		<div class="col-md-8">
	<div class="links btn-group">
		 <%= link_to "Back", root_path, class: "btn btn-custom" %>

		<% if u_ser_signed_in? %>

			<% if @book.u_ser_id == current_u_ser.id %>

				<%= link_to "Edit", edit_book_path(@book), class: "btn btn-custom" %>
				<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are your sure?" }, class: "btn btn-custom" %> 
			<% end %>

		<% end %>
	</div>	

	<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {

			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
	</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',	
		score: function() {

			return $(this).attr('data-score');
		}
	});
	</script>
	</div>
	</div>  