config/routes.rb
Rails.application.routes.draw do
  devise_for :u_sers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :books do
	resources :reviews
end
root 'books#index'

post 'books/search', to: 'books#search'

require 'sidekiq/web'
mount Sidekiq::Web => "/sidekiq"

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_book
	before_action :find_reviews, only: [:edit, :update, :destroy]
	before_action :authenticate_u_ser!, only: [:new, :edit]
	

	def new
		@review = Review.new
	end

	def create 
		@review = Review.new(review_params)	
		@review.book_id = @book.id
		@review.u_ser_id = current_u_ser.id

		if @review.save
			redirect_to book_path(@book)
		else
			render 'new'
		end	
	end


	def edit
	end

	def destroy
		@review.destroy
		redirect_to book_path(@book)
	end


	def update
	if @review.update(review_params)
		redirect_to book_path(@book)
	else
		render 'edit'
	end

	end


	def find_book
	@book = Book.find(params[:book_id])

	end

	def find_reviews
	@review = Review.find(params[:id])

	end

	private

	def review_params
		params.require(:review).permit(:rating, :comment)	
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
<div id="rating-form">
<label>Rating</label>
</div>
<%= f.input :comment %>
<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
</script>   

app/views/reviews/_review.html.erb
<div class="review">

<div class="review-rating" data-score="<%= review.rating %>"></div>
<p class="review-comment"><%= review.comment %></p>
	<% if u_ser_signed_in? %>

		<% if review.u_ser_id == current_u_ser.id %>	

			<div class="links btn-group">
			<li>Sentiment Score is: <%= review.sentiment_score %></li>

			<%= link_to "Edit", edit_book_review_path(review.book, review), class: "btn btn-custom" %>
			<%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-custom" %>	
			</div>

		<% end %>

	<% end %>	

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="edit-review-form">
	<h2>Edit Review </h2>	
	<%= simple_form_for([@book, @review]) do |f| %>
	<div id="rating-form">
	<label>Rating</label>
	</div>
		<%= f.input :comment %>
		<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>

    </div>
</div>		
		<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
	</script>   

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="new-review-form">

	<h1> New Review </h1> 

	<%= render 'form' %>
	</div>
</div>