config/routes.rb
Rails.application.routes.draw do
  devise_for :u_sers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :books do
	resources :reviews
end
root 'books#index'

post 'books/search', to: 'books#search'

require 'sidekiq/web'
mount Sidekiq::Web => "/sidekiq"

end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <nav class= "navbar navbar-default">

   <div class="container">

   <div class="navbar-header">
   <%= link_to "Book review", root_path, class:"navbar-brand" %>
   </div>

   <ul class="nav navbar-nav">
   <li><%= link_to "Sign up", new_u_ser_registration_path %></li>
   <% if u_ser_signed_in? %>
   <li><%= link_to "Sign out", destroy_u_ser_session_path, method: :delete %></li>
   <% else %>
   <li><%= link_to "Log in", new_u_ser_session_path %> </li>
   <% end %>
   </ul>

   <ul class="nav navbar-nav navbar-right">
   <li class="dropdown" >
   <a href="#" class="dropdown-toggle"  data-toggle="dropdown" role="button" aria-expanded="false">Categories<span class="caret"></span></a>
   <ul class="dropdown-menu" role="menu">
   <% Category.all.each do |category| %>
   <li class="<%= 'active' if params[:category] == category.name %>">
   <%= link_to category.name, books_path(category: category.name), class: "link" %>
   </li>
   <% end %>  
   <%= link_to "All", books_path %>
   </ul>
   </li>


   <% if u_ser_signed_in? %>
   <li><%= link_to "Add Book", new_book_path %> </li>
    <li class="navbar-default" ><%= current_u_ser.email %></li>
      <%= form_for(Search.new, url: books_search_path, method: :post) do |f| %>
      <%= f.text_field :search %>
      <%= f.submit%>
      <% end %>
      
  <% end %>
   </ul>
   </div>
   </nav>




   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

   <div class="container" >

    <%= yield %>
  </div>
  </body>
</html>